image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  
before_script:
  - npm install
  - npm --prefix ./functions install
  
build:
  stage: build
  only:
    - master
  tags:
    - npm
    - angular
    - ubuntu
  artifacts:
    paths:
      - dist/
  script:
    - pkill -f node || true
    - npm run build:ssr
    - screen -d -m bash -c "npm run serve:ssr > /var/tmp/server.log 2>&1"