image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  
before_script:
  - npm install
  - npm --prefix ./functions install
  
build:
  stage: build
  only:
    - master
  tags:
    - npm
    - angular
    - ubuntu
  artifacts:
    paths:
      - dist/
  script:
    - npm run build:ssr
    - pkill -f node || true
    - pm2 start dist/questnr-front-end/server/main.js --name questnr1
    - pm2 start dist/questnr-front-end/server/main.js --name questnr2
    - pm2 start dist/questnr-front-end/server/main.js --name questnr3
    - pm2 start dist/questnr-front-end/server/main.js --name questnr4
    - pm2 start dist/questnr-front-end/server/main.js --name questnr5