image: node:latest

stages:
  - build
  
before_script:
  - npm install
  - npm --prefix ./functions install
  
build:
  stage: build
  only:
    - master
  tags:
    - npm
    - angular
    - ubuntu
  artifacts:
    paths:
      - dist/
  script:
    - npm run build:ssr
    - pm2 restart all